### ISSUE TITLE
Most characters don't generate traits

### ISSUE THREAD

**Issue by Rigmored** [Middle-Earth-Project-Team/mod#107]
Only education is generated leaving most characters with no traits at all

**Comment by Lonhaldar** [comment]
Normally it should happens after a few days?

**Comment by Chris1993** [comment]
This is due to:

MAX_GENERATED_TRAITS_FOR_HISTORICAL = 0,		-- Generate random traits up this number for adult historical characters

in defines.lua, we set 0 because we didn't want a Sauron with a "Lustful" trait and stuff like that, but I guess that similar inconveniences may be avoided by adding exclusions in traits potential.

**Comment by Rigmored** [comment]
As long as he has traits already, perhaps it won't generate more than the number set?

**Comment by Chris1993** [comment]
Needs testing, I'll check it out

**Comment by Rigmored** [comment]
Oops

**Comment by Lonhaldar** [comment]
I'm validating and adding back these events currently :)

**Comment by Lonhaldar** [comment]
Done, and commited!
